name: Deploy Static Website to ECS

on:
  push:
    branches:
      - main  # Adjust to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-south-1  # Set region globally for the job
    
    steps:
      # Checkout the code
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Set up Docker Buildx (for building multi-platform images)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to AWS ECR
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t my-static-website .

      # Tag the Docker image
      - name: Tag Docker image
        run: |
          docker tag my-static-website:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-south-1.amazonaws.com/my-static-website:latest

      # Push the Docker image to AWS ECR
      - name: Push Docker image to Amazon ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-south-1.amazonaws.com/my-static-website:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Log in to AWS CLI
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # Update ECS service
      - name: Deploy to ECS
        run: |
          aws ecs update-service --cluster apache-web-cluster --service apache-web-service  --force-new-deployment --region ap-south-1
