name: Build, Push, Deploy to ECS, and Get Public IP

on: 
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build, Push, Deploy to ECS
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out code
        uses: actions/checkout@v2

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # Step 3: Log in to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Step 4: Build, tag, and push the Docker image to Amazon ECR
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: static-html-apache
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      # Step 5: Create ECS Cluster (if not already created)
      - name: Create ECS Cluster
        run: |
          aws ecs create-cluster --cluster-name apache-web-cluster --region ap-south-1 || echo "Cluster already exists"

      # Step 6: Register ECS Task Definition
      - name: Register ECS Task Definition
        run: |
          aws ecs register-task-definition \
            --family static-html-task \
            --execution-role-arn arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/ecsTaskExecutionRole \
            --network-mode awsvpc \
            --container-definitions '[{
                "name": "apache-container",
                "image": "${{ steps.login-ecr.outputs.registry }}/static-html-apache:latest",
                "memory": 512,
                "cpu": 256,
                "essential": true,
                "portMappings": [{"containerPort": 80, "hostPort": 80, "protocol": "tcp"}]
            }]' \
            --requires-compatibilities FARGATE \
            --cpu 256 \
            --memory 512 \
            --region ap-south-1

      # Step 7: Check if the ECS Service already exists
      - name: Check if ECS Service exists
        id: check-service
        run: |
          SERVICE_EXISTS=$(aws ecs describe-services --cluster apache-web-cluster --services apache-web-service --query "services[0].serviceName" --output text)
          echo "Service Exists: $SERVICE_EXISTS"
          echo "service_exists=$SERVICE_EXISTS" >> $GITHUB_ENV

      # Step 8: Create ECS Service if not exists or update if exists
      - name: Create or Update ECS Service
        run: |
          if [ "${{ env.service_exists }}" == "apache-web-service" ]; then
            echo "Service already exists, updating service..."
            aws ecs update-service \
              --cluster apache-web-cluster \
              --service apache-web-service \
              --task-definition static-html-task \
              --desired-count 1 \
              --region ap-south-1
          else
            echo "Service does not exist, creating new service..."
            aws ecs create-service \
              --cluster apache-web-cluster \
              --service-name apache-web-service \
              --task-definition static-html-task \
              --desired-count 1 \
              --launch-type FARGATE \
              --network-configuration "awsvpcConfiguration={subnets=[subnet-06d6437824c554b71],securityGroups=[sg-0d7c9a80b869b0b74],assignPublicIp=ENABLED}" \
              --region ap-south-1
          fi

      # Step 9: Deploy ECS Service (Rolling update)
      - name: Deploy to ECS
        run: |
          aws ecs update-service \
            --cluster apache-web-cluster \
            --service apache-web-service \
            --force-new-deployment \
            --region ap-south-1

      # Step 10: Retrieve the Public IP (Elastic Load Balancer or ECS Task)
      - name: Retrieve Public IP of Application
        id: retrieve-ip
        run: |
          # Check if an ELB is being used (Replace 'your-load-balancer-name' with the actual ELB name)
          ELB_DNS_NAME=$(aws elb describe-load-balancers \
            --query "LoadBalancerDescriptions[?LoadBalancerName=='your-load-balancer-name'].DNSName" \
            --output text)
          
          if [ -n "$ELB_DNS_NAME" ]; then
            echo "ELB DNS Name: $ELB_DNS_NAME"
            echo "Application is accessible at: http://$ELB_DNS_NAME"
          else
            # Fallback to retrieving ECS Task Public IP (for Fargate with public IP enabled)
            TASK_ID=$(aws ecs list-tasks --cluster apache-web-cluster --service-name apache-web-service --query "taskArns[0]" --output text)
            PUBLIC_IP=$(aws ecs describe-tasks \
              --cluster apache-web-cluster \
              --tasks $TASK_ID \
              --query "tasks[0].attachments[0].details[?name=='publicIpv4Address'].value" \
              --output text)
            
            echo "ECS Task Public IP: $PUBLIC_IP"
            echo "Application is accessible at: http://$PUBLIC_IP"
          fi
