name: Build, Push, and Deploy to ECS

on: 
  push:
    branches:
      - main

jobs:
  build:
    name: Build, Push, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: github-push-action
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Generate ECS Task Definition
        run: |
          cat <<EOF > ecs-task-definition.json
          {
            "family": "my-ecs-task",
            "containerDefinitions": [
              {
                "name": "my-container",
                "image": "${{ steps.login-ecr.outputs.registry }}/github-push-action:latest",
                "memory": 512,
                "cpu": 256,
                "essential": true,
                "portMappings": [
                  {
                    "containerPort": 80,
                    "hostPort": 80
                  }
                ]
              }
            ]
          }
          EOF

      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ecs-task-definition.json
          service: web-app-ec2-service
          cluster: web-app-ec2-cluster
          wait-for-service-stability: true

      - name: Retrieve Public IP of ECS Task
        run: |
          # Get the ECS task ID for the running task
          TASK_ID=$(aws ecs list-tasks --cluster web-app-ec2-cluster --service-name web-app-ec2-service --query 'taskArns[0]' --output text)
          
          # Get the ENI (Elastic Network Interface) associated with the ECS task
          ENI_ID=$(aws ecs describe-tasks --cluster web-app-ec2-cluster --tasks $TASK_ID --query 'tasks[0].attachments[0].details[?name==`networkInterfaceId`].value' --output text)
          
          # Retrieve the public IP address associated with the ENI
          PUBLIC_IP=$(aws ec2 describe-network-interfaces --network-interface-ids $ENI_ID --query 'NetworkInterfaces[0].Association.PublicIp' --output text)
          
          echo "Public IP of the ECS task: $PUBLIC_IP"
